USE [CourseProjectCS2];

CREATE TABLE [Users](
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	username NVARCHAR(16) NOT NULL,
);

CREATE TABLE [Chats](
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	name NVARCHAR(16) NOT NULL,
);

CREATE TABLE [UserChat](
	userid INT FOREIGN KEY REFERENCES Users(id) NOT NULL,
	chatid INT FOREIGN KEY REFERENCES Chats(id) NOT NULL,

	CONSTRAINT id PRIMARY KEY(userid, chatid) 
);

CREATE TABLE [Messages](
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	sender INT FOREIGN KEY REFERENCES Users(id) NOT NULL,
	chat INT FOREIGN KEY REFERENCES Chats(id) NOT NULL,
	date DATETIME NOT NULL,
	content NVARCHAR(500) NOT NULL,
);