// <auto-generated />
using System;
using ASPServer.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230802115133__init")]
    partial class _init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPServer.Models.Entity.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5073),
                            Name = "ovo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5077),
                            Name = "ptp"
                        });
                });

            modelBuilder.Entity("ASPServer.Models.Entity.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("ASPServer.Models.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(4868),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(4882),
                            Name = "Bobr"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(4883),
                            Name = "Test"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(4884),
                            Name = "Usver"
                        });
                });

            modelBuilder.Entity("ASPServer.Models.Entity.UserChat", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("UserChats");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ChatId = 1,
                            AddedTime = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5098)
                        },
                        new
                        {
                            UserId = 2,
                            ChatId = 1,
                            AddedTime = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5101)
                        },
                        new
                        {
                            UserId = 3,
                            ChatId = 1,
                            AddedTime = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5102)
                        },
                        new
                        {
                            UserId = 4,
                            ChatId = 1,
                            AddedTime = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5103)
                        },
                        new
                        {
                            UserId = 1,
                            ChatId = 2,
                            AddedTime = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5104)
                        },
                        new
                        {
                            UserId = 2,
                            ChatId = 2,
                            AddedTime = new DateTime(2023, 8, 2, 18, 51, 33, 221, DateTimeKind.Local).AddTicks(5105)
                        });
                });

            modelBuilder.Entity("ASPServer.Models.Entity.Message", b =>
                {
                    b.HasOne("ASPServer.Models.Entity.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("ASPServer.Models.Entity.UserChat", b =>
                {
                    b.HasOne("ASPServer.Models.Entity.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ASPServer.Models.Entity.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASPServer.Models.Entity.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("ASPServer.Models.Entity.User", b =>
                {
                    b.Navigation("UserChats");
                });
#pragma warning restore 612, 618
        }
    }
}
